version: '3.3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - net
    volumes:
      - /home/elofun/novnc/nginx.conf:/etc/nginx/nginx.conf
    #environment:
    #  CHECK_PROXY_UPSTREAM: 0
    #  PROXY_MAP: |
    #    / => novnc_novnc/
  novnc:
    image: hongduylee/novnc:8
    ports:
      - 6081:6081
    networks:
      - net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  net:
